
<P ALIGN=CENTER>
<h4 align=center>
<A HREF="./main.html" onMouseOver = "window.status='Main page with intro, news and announcements.';
return true">Home</A>
<b> | </b>
<A HREF="./software.html" onMouseOver = "window.status='Soar source code and executables for various platforms.' ;
return true">Software</A>
<b> | </b>
<A HREF="./docs.html" onMouseOver = "window.status='Documentation, FAQs, on-line man pages and tutorials.' ;
return true">Documentation</A>
<b> | </b>
<A HREF="./getting-started.html" onMouseOver = "window.status='If you are new to Soar, start here.';
return true">GettingStarted</A>
<b> | </b>
<A HREF="./projects.html" onMouseOver = "window.status='Various soar-related projects (environments, tools, extensions...)' ;
return true">Tools/Projects</A>
<b> | </b>
<A HREF="./groups.html" onMouseOver = "window.status='Links to Soar research institutions and corporations around the world.' ;
return true">Research Groups</A>
<b> | </b>
<A HREF="./contact.html" onMouseOver = "window.status='E-mail addresses, mailing lists and an information request form.' ;
return true">Contact Us</A>
</h4>
</P>


